---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: cloud
...
---
apiVersion: v1
kind: Pod
metadata:
   namespace: dev
   name: mypod
   labels:
     name: myapp
spec:
  containers:
  - name: nginxcon
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
...
---
  apiVersion: v1
  kind: Service
  metadata:
    name: mysvc
  spec:
    selector:
      app: myapp
    ports:
    - port: 80
      targetPort: 80
...
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myrp
  namespace: dev
spec:
  replicas: 5
  selector:
    app: myapp
  template:
    metadata:
      name: mypod1
      labels:
        app: myapp
    spec:
      containers:
      - name: my-kk
        image: nginx
        ports:
        - containerPort: 80
...
